"""Initial migration

Revision ID: 073ad422aab5
Revises: 
Create Date: 2026-07-01 20:53:50.738764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073ad422aab5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_settings_id'), 'api_key_settings', ['id'], unique=False)
    op.create_index(op.f('ix_api_key_settings_service_name'), 'api_key_settings', ['service_name'], unique=True)
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('query_value', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_id'), 'investigations', ['id'], unique=False)
    op.create_index(op.f('ix_investigations_query_type'), 'investigations', ['query_type'], unique=False)
    op.create_index(op.f('ix_investigations_query_value'), 'investigations', ['query_value'], unique=False)
    op.create_index(op.f('ix_investigations_timestamp'), 'investigations', ['timestamp'], unique=False)
    op.create_table('analyst_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('tag_color', sa.String(length=20), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_notes_id'), 'analyst_notes', ['id'], unique=False)
    op.create_index(op.f('ix_analyst_notes_investigation_id'), 'analyst_notes', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_analyst_notes_timestamp'), 'analyst_notes', ['timestamp'], unique=False)
    op.create_table('target_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_results_id'), 'target_results', ['id'], unique=False)
    op.create_index(op.f('ix_target_results_investigation_id'), 'target_results', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_target_results_module_name'), 'target_results', ['module_name'], unique=False)
    op.create_index(op.f('ix_target_results_status'), 'target_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_results_status'), table_name='target_results')
    op.drop_index(op.f('ix_target_results_module_name'), table_name='target_results')
    op.drop_index(op.f('ix_target_results_investigation_id'), table_name='target_results')
    op.drop_index(op.f('ix_target_results_id'), table_name='target_results')
    op.drop_table('target_results')
    op.drop_index(op.f('ix_analyst_notes_timestamp'), table_name='analyst_notes')
    op.drop_index(op.f('ix_analyst_notes_investigation_id'), table_name='analyst_notes')
    op.drop_index(op.f('ix_analyst_notes_id'), table_name='analyst_notes')
    op.drop_table('analyst_notes')
    op.drop_index(op.f('ix_investigations_timestamp'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_query_value'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_query_type'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_api_key_settings_service_name'), table_name='api_key_settings')
    op.drop_index(op.f('ix_api_key_settings_id'), table_name='api_key_settings')
    op.drop_table('api_key_settings')
    # ### end Alembic commands ###
